// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "footballui-20181229105141-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://footballui-20181229105141-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:85d6ae4b-e6c1-4fa7-bdc6-61190a47cd7f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7qCS3irDf",
    "aws_user_pools_web_client_id": "1gm6nj64tm4q54v8srcp7c0ngq",
    "aws_user_files_s3_bucket": "footballuiee16b5a485c749d3a07c77df99e0b047",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
