/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:72bfb6bf-79c3-4872-a55f-4d87f2075a66",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RMWoyKwmg",
    "aws_user_pools_web_client_id": "n06h6c1qc05k6d9l1l7o4deql",
    "oauth": {},
    "aws_content_delivery_bucket": "nflplayoffui-20201230131151-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://nflplayoffui-20201230131151-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_user_files_s3_bucket": "nflplayoffuif60c1d934e0a46e8a321debb5ee95287130734-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
