// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:36b7768b-c628-4172-91ff-66b290aed0f3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7MujoN3uX",
    "aws_user_pools_web_client_id": "7jjaov0hnc66m08kro50hcuimu",
    "oauth": {},
    "aws_user_files_s3_bucket": "nfl-playoff-ui5fdb9a29c0d947e5831d23def2e3a795-ci",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "footballui-20181229105141-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://footballui-20181229105141-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
